export const SOIL_TYPES_DB = [
  { id: 'alluvial', nameEn: 'Alluvial Soil', nameTa: 'வண்டல் மண்', typicalGs: [2.60, 2.70], typicalPH: [6.5, 8.0], typicalEC: [0.1, 1.0], typicalOC: [0.5, 1.5], typicalCEC: [10, 25], description: 'Fertile river deposits, rich in potash but poor in phosphorus.', suitableCrops: ['paddy', 'sugarcane', 'cotton', 'banana', 'jute'] },
  { id: 'black', nameEn: 'Black Soil (Regur)', nameTa: 'கரிசல் மண்', typicalGs: [2.60, 2.80], typicalPH: [7.0, 8.5], typicalEC: [0.2, 1.5], typicalOC: [0.3, 0.8], typicalCEC: [30, 50], description: 'High clay content, swells when wet, cracks when dry, high moisture retention.', suitableCrops: ['cotton', 'sorghum', 'sunflower', 'chillies', 'coriander'] },
  { id: 'red_yellow', nameEn: 'Red and Yellow Soil', nameTa: 'செம்மண் மற்றும் மஞ்சள் மண்', typicalGs: [2.65, 2.75], typicalPH: [5.5, 7.0], typicalEC: [0.1, 0.5], typicalOC: [0.2, 0.6], typicalCEC: [5, 15], description: 'Iron-rich, porous, friable structure, absence of lime and kankar.', suitableCrops: ['groundnut', 'potato', 'pearl_millet', 'red_gram', 'tobacco'] },
  { id: 'laterite', nameEn: 'Laterite Soil', nameTa: 'சரளை மண்', typicalGs: [2.55, 2.70], typicalPH: [5.0, 6.5], typicalEC: [0.1, 0.4], typicalOC: [0.3, 1.0], typicalCEC: [3, 10], description: 'Leached, acidic, poor in organic matter, nitrogen, phosphate and calcium.', suitableCrops: ['tea', 'coffee', 'rubber', 'cashew', 'tapioca'] },
  { id: 'arid', nameEn: 'Arid (Desert) Soil', nameTa: 'பாலைவன மண்', typicalGs: [2.65, 2.70], typicalPH: [7.5, 9.0], typicalEC: [1.0, 4.0], typicalOC: [0.1, 0.3], typicalCEC: [5, 15], description: 'Sandy, low OC, high soluble salts, alkaline nature.', suitableCrops: ['pearl_millet', 'sorghum', 'sesame', 'cluster_beans', 'mustard'] },
  { id: 'forest_mountain', nameEn: 'Forest and Mountain Soil', nameTa: 'காடு மற்றும் மலை மண்', typicalGs: [2.40, 2.65], typicalPH: [5.0, 6.5], typicalEC: [0.1, 0.5], typicalOC: [1.5, 3.5], typicalCEC: [15, 30], description: 'High OC, rich in humus, acidic character, good for plantations.', suitableCrops: ['tea', 'coffee', 'spices', 'fruits', 'maize'] },
  { id: 'saline_alkaline', nameEn: 'Saline and Alkaline Soil', nameTa: 'உவர் மற்றும் கார மண்', typicalGs: [2.60, 2.70], typicalPH: [8.0, 10.0], typicalEC: [4.0, 15.0], typicalOC: [0.1, 0.5], typicalCEC: [10, 20], description: 'High EC, excess sodium, poor drainage, unfit for most crops without reclamation.', suitableCrops: ['cotton', 'barley', 'sugarbeet', 'dates', 'wheat'] },
  { id: 'peaty_marshy', nameEn: 'Peaty and Marshy Soil', nameTa: 'கரிம மற்றும் சதுப்பு மண்', typicalGs: [1.50, 2.20], typicalPH: [4.0, 6.0], typicalEC: [0.5, 2.0], typicalOC: [3.5, 10.0], typicalCEC: [30, 60], description: 'Very high OC, dark, heavy and highly acidic.', suitableCrops: ['paddy', 'mangroves'] }
];

export const CROPS_DB = [
  { id: 'paddy', nameEn: 'Paddy', nameTa: 'நெல்', category: 'crop', targetN: 120, targetP: 40, targetK: 40, idealPH: [5.5, 7.5], idealEC: [0, 3], idealMoisture: [60, 100], idealSoilTypes: ['alluvial', 'peaty_marshy', 'black'], waterReqEn: 'High', waterReqTa: 'அதிகம்', seasonEn: 'Kharif', seasonTa: 'கார்/குறுவை' },
  { id: 'sorghum', nameEn: 'Sorghum/Cholam', nameTa: 'சோளம்', category: 'crop', targetN: 90, targetP: 45, targetK: 45, idealPH: [6.0, 8.5], idealEC: [0, 4], idealMoisture: [30, 60], idealSoilTypes: ['black', 'red_yellow', 'arid'], waterReqEn: 'Low', waterReqTa: 'குறைவு', seasonEn: 'Kharif/Rabi', seasonTa: 'கார்/பசலி' },
  { id: 'finger_millet', nameEn: 'Finger Millet/Ragi', nameTa: 'கேழ்வரகு', category: 'crop', targetN: 60, targetP: 30, targetK: 30, idealPH: [5.0, 8.2], idealEC: [0, 2.5], idealMoisture: [40, 70], idealSoilTypes: ['red_yellow', 'alluvial', 'laterite'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Kharif', seasonTa: 'கார்' },
  { id: 'pearl_millet', nameEn: 'Pearl Millet/Cumbu', nameTa: 'கம்பு', category: 'crop', targetN: 70, targetP: 35, targetK: 35, idealPH: [6.0, 8.5], idealEC: [0, 3.5], idealMoisture: [20, 50], idealSoilTypes: ['arid', 'red_yellow', 'black'], waterReqEn: 'Low', waterReqTa: 'குறைவு', seasonEn: 'Kharif', seasonTa: 'கார்' },
  { id: 'black_gram', nameEn: 'Black Gram', nameTa: 'உளுந்து', category: 'crop', targetN: 20, targetP: 40, targetK: 20, idealPH: [5.5, 7.5], idealEC: [0, 2], idealMoisture: [40, 60], idealSoilTypes: ['black', 'red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Kharif/Rabi', seasonTa: 'கார்/பசலி' },
  { id: 'green_gram', nameEn: 'Green Gram', nameTa: 'பச்சைப்பயறு', category: 'crop', targetN: 20, targetP: 40, targetK: 20, idealPH: [6.0, 7.5], idealEC: [0, 2], idealMoisture: [40, 60], idealSoilTypes: ['alluvial', 'black', 'red_yellow'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Kharif/Zaid', seasonTa: 'கார்/கோடை' },
  { id: 'red_gram', nameEn: 'Red Gram/Toor', nameTa: 'துவரை', category: 'crop', targetN: 25, targetP: 50, targetK: 25, idealPH: [6.0, 7.5], idealEC: [0, 2.5], idealMoisture: [40, 65], idealSoilTypes: ['red_yellow', 'black', 'laterite'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Kharif', seasonTa: 'கார்' },
  { id: 'sugarcane', nameEn: 'Sugarcane', nameTa: 'கரும்பு', category: 'crop', targetN: 250, targetP: 100, targetK: 120, idealPH: [6.5, 8.0], idealEC: [0, 3], idealMoisture: [70, 90], idealSoilTypes: ['alluvial', 'black', 'red_yellow'], waterReqEn: 'Very High', waterReqTa: 'மிக அதிகம்', seasonEn: 'Annual', seasonTa: 'ஆண்டுமுழுவதும்' },
  { id: 'cotton', nameEn: 'Cotton', nameTa: 'பருத்தி', category: 'crop', targetN: 120, targetP: 60, targetK: 60, idealPH: [6.0, 8.0], idealEC: [0, 4.5], idealMoisture: [50, 70], idealSoilTypes: ['black', 'alluvial', 'saline_alkaline'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Kharif', seasonTa: 'கார்' },
  { id: 'tobacco', nameEn: 'Tobacco', nameTa: 'புகையிலை', category: 'crop', targetN: 100, targetP: 60, targetK: 80, idealPH: [5.5, 6.5], idealEC: [0, 2], idealMoisture: [50, 75], idealSoilTypes: ['red_yellow', 'alluvial', 'laterite'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Rabi', seasonTa: 'பசலி' },
  { id: 'groundnut', nameEn: 'Groundnut', nameTa: 'நிலக்கடலை', category: 'crop', targetN: 25, targetP: 50, targetK: 75, idealPH: [6.0, 7.0], idealEC: [0, 2.5], idealMoisture: [40, 60], idealSoilTypes: ['red_yellow', 'alluvial', 'arid'], waterReqEn: 'Low to Medium', waterReqTa: 'குறைவு முதல் மிதமானது', seasonEn: 'Kharif', seasonTa: 'கார்' },
  { id: 'sesame', nameEn: 'Sesame', nameTa: 'எள்', category: 'crop', targetN: 40, targetP: 40, targetK: 40, idealPH: [5.5, 8.0], idealEC: [0, 2], idealMoisture: [30, 50], idealSoilTypes: ['arid', 'red_yellow', 'alluvial'], waterReqEn: 'Low', waterReqTa: 'குறைவு', seasonEn: 'Kharif/Zaid', seasonTa: 'கார்/கோடை' },
  { id: 'coconut', nameEn: 'Coconut', nameTa: 'தென்னை', category: 'crop', targetN: 500, targetP: 320, targetK: 1200, idealPH: [5.2, 8.0], idealEC: [0, 4], idealMoisture: [60, 85], idealSoilTypes: ['alluvial', 'red_yellow', 'laterite'], waterReqEn: 'High', waterReqTa: 'அதிகம்', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'sunflower', nameEn: 'Sunflower', nameTa: 'சூரியகாந்தி', category: 'crop', targetN: 60, targetP: 40, targetK: 40, idealPH: [6.5, 8.0], idealEC: [0, 3], idealMoisture: [40, 65], idealSoilTypes: ['black', 'red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Zaid', seasonTa: 'கோடை' },
  { id: 'tea', nameEn: 'Tea', nameTa: 'தேயிலை', category: 'crop', targetN: 150, targetP: 50, targetK: 100, idealPH: [4.5, 5.5], idealEC: [0, 1.5], idealMoisture: [70, 95], idealSoilTypes: ['laterite', 'forest_mountain'], waterReqEn: 'High', waterReqTa: 'அதிகம்', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'coffee', nameEn: 'Coffee', nameTa: 'காபி', category: 'crop', targetN: 100, targetP: 45, targetK: 100, idealPH: [5.5, 6.5], idealEC: [0, 1.5], idealMoisture: [65, 90], idealSoilTypes: ['forest_mountain', 'laterite'], waterReqEn: 'High', waterReqTa: 'அதிகம்', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'rubber', nameEn: 'Rubber', nameTa: 'ரப்பர்', category: 'crop', targetN: 60, targetP: 30, targetK: 30, idealPH: [4.5, 6.0], idealEC: [0, 1], idealMoisture: [70, 100], idealSoilTypes: ['laterite', 'red_yellow'], waterReqEn: 'Very High', waterReqTa: 'மிக அதிகம்', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'tapioca', nameEn: 'Tapioca/Cassava', nameTa: 'மரவள்ளிக்கிழங்கு', category: 'crop', targetN: 90, targetP: 40, targetK: 140, idealPH: [5.5, 7.0], idealEC: [0, 1.5], idealMoisture: [40, 70], idealSoilTypes: ['laterite', 'red_yellow'], waterReqEn: 'Low to Medium', waterReqTa: 'குறைவு முதல் மிதமானது', seasonEn: 'Kharif', seasonTa: 'கார்' }
];

export const VEGETABLES_DB = [
  { id: 'tomato', nameEn: 'Tomato', nameTa: 'தக்காளி', category: 'vegetable', targetN: 100, targetP: 50, targetK: 50, idealPH: [6.0, 7.0], idealEC: [0, 2.5], idealMoisture: [50, 75], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'All seasons', seasonTa: 'எல்லா காலங்களும்' },
  { id: 'brinjal', nameEn: 'Brinjal/Eggplant', nameTa: 'கத்திரிக்காய்', category: 'vegetable', targetN: 100, targetP: 50, targetK: 50, idealPH: [5.5, 6.8], idealEC: [0, 2], idealMoisture: [50, 75], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'All seasons', seasonTa: 'எல்லா காலங்களும்' },
  { id: 'chillies', nameEn: 'Chillies', nameTa: 'மிளகாய்', category: 'vegetable', targetN: 120, targetP: 60, targetK: 60, idealPH: [6.0, 7.5], idealEC: [0, 2.5], idealMoisture: [45, 70], idealSoilTypes: ['black', 'red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'All seasons', seasonTa: 'எல்லா காலங்களும்' },
  { id: 'small_onions', nameEn: 'Small Onions/Shallots', nameTa: 'சின்ன வெங்காயம்', category: 'vegetable', targetN: 60, targetP: 60, targetK: 60, idealPH: [6.0, 7.0], idealEC: [0, 2], idealMoisture: [45, 70], idealSoilTypes: ['red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'All seasons', seasonTa: 'எல்லா காலங்களும்' },
  { id: 'ladys_finger', nameEn: "Lady's Finger/Okra", nameTa: 'வெண்டைக்காய்', category: 'vegetable', targetN: 40, targetP: 50, targetK: 30, idealPH: [6.0, 6.8], idealEC: [0, 2], idealMoisture: [50, 75], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'All seasons', seasonTa: 'எல்லா காலங்களும்' },
  { id: 'bitter_gourd', nameEn: 'Bitter Gourd', nameTa: 'பாகற்காய்', category: 'vegetable', targetN: 50, targetP: 50, targetK: 50, idealPH: [6.0, 7.0], idealEC: [0, 2], idealMoisture: [55, 80], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'All seasons', seasonTa: 'எல்லா காலங்களும்' },
  { id: 'bottle_gourd', nameEn: 'Bottle Gourd', nameTa: 'சுரைக்காய்', category: 'vegetable', targetN: 60, targetP: 30, targetK: 30, idealPH: [6.5, 7.5], idealEC: [0, 2], idealMoisture: [55, 80], idealSoilTypes: ['red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'All seasons', seasonTa: 'எல்லா காலங்களும்' },
  { id: 'snake_gourd', nameEn: 'Snake Gourd', nameTa: 'புடலங்காய்', category: 'vegetable', targetN: 50, targetP: 50, targetK: 50, idealPH: [6.0, 7.0], idealEC: [0, 2], idealMoisture: [55, 80], idealSoilTypes: ['red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'All seasons', seasonTa: 'எல்லா காலங்களும்' },
  { id: 'moringa', nameEn: 'Moringa/Drumstick', nameTa: 'முருங்கை', category: 'vegetable', targetN: 100, targetP: 100, targetK: 100, idealPH: [6.0, 7.5], idealEC: [0, 3], idealMoisture: [30, 60], idealSoilTypes: ['red_yellow', 'alluvial', 'arid'], waterReqEn: 'Low', waterReqTa: 'குறைவு', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'potato', nameEn: 'Potato', nameTa: 'உருளைக்கிழங்கு', category: 'vegetable', targetN: 120, targetP: 100, targetK: 120, idealPH: [5.0, 6.5], idealEC: [0, 2], idealMoisture: [60, 85], idealSoilTypes: ['red_yellow', 'laterite', 'alluvial'], waterReqEn: 'High', waterReqTa: 'அதிகம்', seasonEn: 'Rabi', seasonTa: 'பசலி' },
  { id: 'carrot', nameEn: 'Carrot', nameTa: 'கேரட்', category: 'vegetable', targetN: 90, targetP: 90, targetK: 90, idealPH: [5.5, 7.0], idealEC: [0, 1.5], idealMoisture: [55, 80], idealSoilTypes: ['red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Rabi', seasonTa: 'பசலி' },
  { id: 'cabbage', nameEn: 'Cabbage', nameTa: 'முட்டைகோஸ்', category: 'vegetable', targetN: 150, targetP: 100, targetK: 100, idealPH: [6.0, 7.5], idealEC: [0, 2.5], idealMoisture: [60, 85], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium to High', waterReqTa: 'மிதமானது முதல் அதிகம்', seasonEn: 'Rabi', seasonTa: 'பசலி' },
  { id: 'cauliflower', nameEn: 'Cauliflower', nameTa: 'காலிஃப்ளவர்', category: 'vegetable', targetN: 150, targetP: 100, targetK: 100, idealPH: [6.0, 7.0], idealEC: [0, 2.5], idealMoisture: [60, 85], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium to High', waterReqTa: 'மிதமானது முதல் அதிகம்', seasonEn: 'Rabi', seasonTa: 'பசலி' },
  { id: 'garlic', nameEn: 'Garlic', nameTa: 'பூண்டு', category: 'vegetable', targetN: 100, targetP: 50, targetK: 50, idealPH: [6.0, 7.5], idealEC: [0, 2], idealMoisture: [45, 70], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Rabi', seasonTa: 'பசலி' }
];

export const FRUITS_DB = [
  { id: 'banana', nameEn: 'Banana', nameTa: 'வாழை', category: 'fruit', targetN: 200, targetP: 50, targetK: 400, idealPH: [5.5, 7.0], idealEC: [0, 2.5], idealMoisture: [70, 95], idealSoilTypes: ['alluvial', 'red_yellow', 'black'], waterReqEn: 'Very High', waterReqTa: 'மிக அதிகம்', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'mango', nameEn: 'Mango', nameTa: 'மாம்பழம்', category: 'fruit', targetN: 150, targetP: 150, targetK: 150, idealPH: [5.5, 7.5], idealEC: [0, 3], idealMoisture: [40, 75], idealSoilTypes: ['red_yellow', 'alluvial', 'laterite'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'acid_lime', nameEn: 'Acid Lime', nameTa: 'எலுமிச்சை', category: 'fruit', targetN: 400, targetP: 200, targetK: 300, idealPH: [5.5, 7.5], idealEC: [0, 2.5], idealMoisture: [50, 80], idealSoilTypes: ['red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'mandarin_orange', nameEn: 'Mandarin Orange', nameTa: 'கமலா ஆரஞ்சு', category: 'fruit', targetN: 400, targetP: 200, targetK: 300, idealPH: [6.0, 7.5], idealEC: [0, 2], idealMoisture: [50, 80], idealSoilTypes: ['red_yellow', 'alluvial', 'forest_mountain'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'papaya', nameEn: 'Papaya', nameTa: 'பப்பாளி', category: 'fruit', targetN: 250, targetP: 250, targetK: 500, idealPH: [6.0, 7.0], idealEC: [0, 2], idealMoisture: [50, 80], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'guava', nameEn: 'Guava', nameTa: 'கொய்யா', category: 'fruit', targetN: 300, targetP: 150, targetK: 150, idealPH: [6.0, 7.5], idealEC: [0, 4], idealMoisture: [45, 75], idealSoilTypes: ['red_yellow', 'alluvial', 'black', 'arid'], waterReqEn: 'Low to Medium', waterReqTa: 'குறைவு முதல் மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'sapota', nameEn: 'Sapota/Chiku', nameTa: 'சப்போட்டா', category: 'fruit', targetN: 600, targetP: 200, targetK: 200, idealPH: [6.0, 8.0], idealEC: [0, 3], idealMoisture: [50, 80], idealSoilTypes: ['red_yellow', 'alluvial', 'black'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'jackfruit', nameEn: 'Jackfruit', nameTa: 'பலாப்பழம்', category: 'fruit', targetN: 200, targetP: 120, targetK: 100, idealPH: [6.0, 7.5], idealEC: [0, 2.5], idealMoisture: [50, 85], idealSoilTypes: ['red_yellow', 'laterite', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'grapes', nameEn: 'Grapes', nameTa: 'திராட்சை', category: 'fruit', targetN: 200, targetP: 100, targetK: 300, idealPH: [6.5, 7.5], idealEC: [0, 2], idealMoisture: [45, 75], idealSoilTypes: ['red_yellow', 'alluvial'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'plums', nameEn: 'Plums', nameTa: 'ஆல்பக்கோடா', category: 'fruit', targetN: 300, targetP: 150, targetK: 200, idealPH: [5.5, 6.5], idealEC: [0, 1.5], idealMoisture: [55, 80], idealSoilTypes: ['forest_mountain', 'red_yellow'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'peaches', nameEn: 'Peaches', nameTa: 'பீச்', category: 'fruit', targetN: 350, targetP: 150, targetK: 300, idealPH: [5.5, 6.5], idealEC: [0, 1.5], idealMoisture: [55, 80], idealSoilTypes: ['forest_mountain', 'red_yellow'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'pears', nameEn: 'Pears', nameTa: 'பேரிக்காய்', category: 'fruit', targetN: 300, targetP: 150, targetK: 250, idealPH: [6.0, 7.0], idealEC: [0, 1.5], idealMoisture: [60, 85], idealSoilTypes: ['forest_mountain', 'red_yellow'], waterReqEn: 'Medium', waterReqTa: 'மிதமானது', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' },
  { id: 'strawberries', nameEn: 'Strawberries', nameTa: 'ஸ்ட்ராபெர்ரி', category: 'fruit', targetN: 150, targetP: 100, targetK: 120, idealPH: [5.5, 6.5], idealEC: [0, 1.5], idealMoisture: [65, 90], idealSoilTypes: ['forest_mountain', 'red_yellow'], waterReqEn: 'Medium to High', waterReqTa: 'மிதமானது முதல் அதிகம்', seasonEn: 'Perennial', seasonTa: 'பல்லாண்டு' }
];

export const ALL_PLANTS_DB = [...CROPS_DB, ...VEGETABLES_DB, ...FRUITS_DB];
